### ISSUE TITLE
[Bug]: ci failed: current mo-service has already crashed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10164]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3202598377d0477da27cb2d23f1bdf8c75580930
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/matrixone/actions/runs/5329195366/jobs/9654636602?pr=10098
<img width="1268" alt="企业微信截图_52426013-bebe-484c-bb5c-1912906b95cd" src="https://github.com/matrixorigin/matrixone/assets/113406637/5f091160-6827-47ed-89c3-473ee10c1dfd">
<img width="1246" alt="企业微信截图_f69f3175-b782-4e12-80af-1aec264a6e1e" src="https://github.com/matrixorigin/matrixone/assets/113406637/2e132fa2-fc61-4c21-8781-acae60eefee3">

2023-06-21 01:55:26 ERROR Executor:169 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/dml/show/show.test][row:45][show table status from db11111111111;] MO does not return result in 120000 ms,con[id=0, user=dump, ***
2023-06-21 01:55:26 ERROR Executor:179 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/dml/show/show.test][row:45][show table status from db11111111111;] was executed failed, con[id=0, user=dump, ***
2023-06-21 01:55:26 ERROR Executor:181 - [EXPECT RESULT]:
Name    Engine    Row_format    Rows    Avg_row_length    Data_length    Max_data_length    Index_length    Data_free    Auto_increment    Create_time    Update_time    Check_time    Collation    Checksum    Create_options    Comment
2023-06-21 01:55:26 ERROR Executor:182 - [ACTUAL RESULT]:
MO does not return result in 120000 ms. 

mo.log:
<img width="1460" alt="WeChatWorkScreenshot_85d94b10-1a02-4067-b587-07c344b5e28a" src="https://github.com/matrixorigin/matrixone/assets/113406637/be450d41-9d3e-45ff-83fd-a9e221136270">
[mo-service.log](https://github.com/matrixorigin/matrixone/files/11811690/mo-service.log)

**Comment by xzxiong** [comment]
@volgariver6 ptal, panic position:
![image](https://github.com/matrixorigin/matrixone/assets/3927687/388ac1d2-c4b6-4527-88ba-363542707085)

**Comment by gouhongshen** [comment]
In the function: [pkg/proxy/my_sql_conn_buf.go::preRecv:](https://github.com/matrixorigin/matrixone/blob/d29764ae18b6b6a5faf8db745b7a9b32a840b2e5/pkg/proxy/mysql_conn_buf.go#L139)

The variable `cmd` may go out of bounds if `b.receiveAtLeast(mysqlHeadLen)` reads exactly mysqlHeadLen bytes.

In typical scenarios, `cmd` is not equal to `cmdQuery` or any other meaningful segment, but it may mistakenly decode previous records as `cmdQuery` due to unclear previous reads.

Therefore, when this situation occurs, `isStmtCommit(b.buf[b.begin+preRecvLen:b.end])` and `isStmtRollback(b.buf[b.begin+preRecvLen:b.end])` will go out of bounds.

**Comment by volgariver6** [comment]
fixed by #10486

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
confirm https://github.com/matrixorigin/MO-Cloud/issues/957 closed
