### ISSUE TITLE
[Feature Request]: Support CREATE TABLE AS SELECT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10362]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

CREATE [TEMPORARY] TABLE [ IF NOT EXISTS ] table_name
 [ (column_name [, ...] ) ]   AS {query}

Query can be any select statement in MO syntax.

SELECT
    [ALL | DISTINCT ]
    select_expr [, select_expr] [[AS] alias] ...
    [INTO variable [, ...]]
    [FROM table_references
    [WHERE where_condition]
    [GROUP BY {col_name | expr | position}
      [ASC | DESC]]
    [HAVING where_condition]
    [ORDER BY {col_name | expr | position}
      [ASC | DESC]] [ NULLS { FIRST | LAST } ]
    [LIMIT {[offset,] row_count | row_count OFFSET offset}]

**Comment by lacrimosaprinz** [comment]
Related documentations:
- Feature list: add new content of `CREATE TABLE AS SELECT`
- Reference Doc: add new doc of `CREATE TABLE AS SELECT`

**Comment by dengn** [comment]
> Related documentation: @dengn pls review and check 👇🏻
> 
> * Feature list: add new content of `CREATE TABLE AS SELECT`
> * MySQL Compatibility: add new content of  `CREATE TABLE AS SELECT`
> * Release note: add new feature of `CREATE TABLE AS SELECT`
> * Reference Doc: add new doc of `CREATE TABLE AS SELECT`

develop guide --> schema design as well.

**Comment by dengn** [comment]
> ### Is there an existing issue for the same feature request?
> * [x]  I have checked the existing issues.
> 
> ### Is your feature request related to a problem?
> _No response_
> 
> ### Describe the feature you'd like
> CREATE [TEMPORARY] TABLE [ IF NOT EXISTS ] table_name [ (column_name [, ...] ) ] AS {query}
> 
> Query can be any select statement in MO syntax.
> 
> SELECT [ALL | DISTINCT ] select_expr [, select_expr] [[AS] alias] ... [INTO variable [, ...]] [FROM table_references [WHERE where_condition] [GROUP BY {col_name | expr | position} [ASC | DESC]] [HAVING where_condition] [ORDER BY {col_name | expr | position} [ASC | DESC]] [ NULLS { FIRST | LAST } ] [LIMIT {[offset,] row_count | row_count OFFSET offset}]
> 
> ### Describe implementation you've considered
> _No response_
> 
> ### Documentation, Adoption, Use Case, Migration Strategy
> _No response_
> 
> ### Additional information
> _No response_

this looks like a lot of syntax. Please specify if it's a complete or partial implementation.

**Comment by domingozhang** [comment]
All syntax is to be implemented

**Comment by dengn** [comment]
All select syntax will be supported with "CREATA TABLE AS SELECT".

**Comment by dengn** [comment]
Due to transactional limit, this "Create table as select" will be implemented as two statements execution:

create table... and insert into table as select...

So transactional atomity is not guaranteed in this statement. It may occurs some situation like:
1. create table t1 is successful and committed. 
2. insert into t1 as select is not successful. 

Users may find the table still remains. this behavior is the same as MySQL prior to 8.0.21 version. 

That limitation is removed in MySQL 8.0.21. On storage engines that support atomic DDL, [CREATE TABLE ... SELECT](https://dev.mysql.com/doc/refman/8.0/en/create-table-select.html) is now recorded and applied as one transaction when row-based replication is in use.

**Comment by ck89119** [comment]
design doc: https://github.com/matrixorigin/docs/blob/main/design/mo/sql/20240226-ck89119-create_table_as_select.md

**Comment by dengn** [comment]
doc edit phase @yangj1211
