### ISSUE TITLE
[Bug]: Allocate too large mem in tpch 100G

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10707]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/mo-auto-test/actions/runs/5560060975/jobs/10156777276

**Comment by aunjgr** [comment]
I've run TPC-H q7 for 100 times and still can't catch it.

Is there any other CI jobs fail on this issue? I want to know if other queries trigger this issue too.

**Comment by aunjgr** [comment]
Still can't observe it. But I suspect it's metadata not being flushed before the first run for some reason.

@badboynt1 Currently we will get bad join order for many TPC-H queries if we don't wait for several minutes after data loading ends. That's annoying for not only customers but also developers like our own. We should avoid bad join order as much as possible by taking account of both stats and DDL constraints.

@zhangxu19830126 Can we downgrade the severity to s0 since it's very rare?

**Comment by aunjgr** [comment]
working on a PR for better debugging info

**Comment by aunjgr** [comment]
haven't reproduce. working on PR.

**Comment by aunjgr** [comment]
can't reproduce

**Comment by aunjgr** [comment]
degrade to s1 since no reproduce
