### ISSUE TITLE
[Bug]: The new column is successfully added as the primary key column.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11252]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b0002bfac60998670ed15b164f51e44ada872697
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1899" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/810fc3c6-fe5d-430d-861e-d906c2ef1ead">

### Steps to Reproduce

```Markdown
drop table if exists mix01;
create table mix01 (col1 int not null , col2 decimal, col3 date, col4 varchar(100));
insert into mix01 values (1, 23849234.324, '2100-01-01', 'qy83uhfbh234y78y&*%^&%$$$E%^&Y*UIJNHBGVFTY^&Y*UJHBGVTF^&*U(OK');
insert into mix01 values (2, 773892.32748000000000, '1997-01-13', '38782yhbf3uhy4iendb32gefdc7y834uh2neujdr2h4f3v43');
insert into mix01 values (3, -82913942.3434, null, null);
select * from mix01;

alter table mix01 add column col5 int primary key ;
```

**Comment by aronchanisme** [comment]
**Expected Behavior**
Add a new column to a non-empty table and also specify the new column as the primary key, should throw an error like mysql does: `ERROR 1062 (23000): Duplicate entry '0' for key 'mix01.PRIMARY'`
This is because for the existing data, the value of the newly added column can only be null. Thus, the newly added column cannot be specified as a primary key(which is not nullable). 

**Actual Behavior**
Mo accepts the sql `alter table mix01 add column col5 int primary key ;` but not throw an error. And the value of this newly added column is null, so for these existing data there will have some issues when it's also specified as a primary key, for example when use does a select operation.

**Comment by aronchanisme** [comment]
<img width="803" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/98e6faf0-2308-4e29-9a8d-0c5757ba1e14">
<img width="809" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/9de4867a-346b-4bf8-8ae3-03a9ca885563">

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Processing

**Comment by qingxinhome** [comment]
The issue has been resolved, please test and verify @aronchanisme @Ariznawlll @sukki37 @daviszhen

**Comment by Ariznawlll** [comment]
<img width="1097" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/df1cf312-a139-4c10-80e7-4aa17ee030e3">

Verified!
