### ISSUE TITLE
[Bug]: select * from table after alter table error in pessimistic mode.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11279]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):32f862c422a4b9b52a315a36a63279b06ecc40f1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="787" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/074a86ba-23a7-4860-aa90-9c308e65d1e8">

### Expected Behavior

<img width="313" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/7cfeb346-17bd-4841-a0f9-ea78923cc080">

**Comment by aronchanisme** [comment]
Verifying expected behavior. @Ariznawlll  Could you please re-upload the screenshot as it seems to be broken.
However, from the actual behavior screenshot, `table does not exist` error is thrown within the transaction after `begin`, but  the table is already created before `begin` statement, so this is a strage error.

**Comment by aronchanisme** [comment]
@qingxinhome Could you please kindly help take a look? Thanks.

**Comment by qingxinhome** [comment]
association #11213

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @daviszhen @Ariznawlll @aronchanisme

**Comment by Ariznawlll** [comment]
<img width="1076" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6708f6c5-0344-4440-909f-107b71a08785">
Verified！
