### ISSUE TITLE
[Bug]: enum type: the result of sort operation is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11348]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0ef31f1816a5f082efdfc49ab0c94ebda743eaa9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="519" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2f764b28-033d-4833-ae5b-3f2184e3939f">

### Expected Behavior

<img width="478" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ce3a03e1-4c77-4a30-bd80-b54d3c775531">

### Steps to Reproduce

```Markdown
drop table if exists builtin01;
create table builtin01(col1 enum('  云原生数据库  ','存储引擎 TAE', 'database system') not null primary key,col2 enum(' database','engine ','index meta data'));
insert into builtin01 values('  云原生数据库  ',' database');
insert into builtin01 values('存储引擎 TAE','engine ');
insert into builtin01 values('database system','engine ');
select * from builtin01;

select max(col1), max(col2) from builtin01;
```

**Comment by sukki37** [comment]
The execution results are the same as MySQL.

**Comment by allengaoo** [comment]
刚才查看了以下， mysql 的online doc：https://dev.mysql.com/doc/refman/8.0/en/enum.html#enum-sorting

根据文档中的以下描述， mysql 对于枚举类型的列排序，是定义列的时候，枚举值出现的先后顺序来排序的。 如果希望按照字符串的规则来排序的话，可以在order by 子句中使用CAST(col_name) 来进行处理。  以下是mysql 的文档内容：
Enumeration Sorting
ENUM values are sorted based on their index numbers, which depend on the order in which the enumeration members were listed in the column specification. For example, 'b' sorts before 'a' for ENUM('b', 'a'). The empty string sorts before nonempty strings, and NULL values sort before all other enumeration values.

To prevent unexpected results when using the ORDER BY clause on an ENUM column, use one of these techniques:

Specify the ENUM list in alphabetic order.

Make sure that the column is sorted lexically rather than by index number by coding ORDER BY CAST(col AS CHAR) or ORDER BY CONCAT(col).


所以，看起来是mysql 自己的实现有bug。 

对于这种情况，建议MO 不需要去参考 mysql 的bug 行为， 直接按照当前行为进行排序即可。 如果用户需要字符类型的排序，可以参考mysql 的文档中的做法，使用CAST。
