### ISSUE TITLE
[Enhancement]: mo can boot from the already existed data

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#11402]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
mo can boot from the existed data.
```

### Why is this needed ?

we can reuse the data generated by the another mo.
the data may be backup or left after failure by the another mo.

### Additional information

suggested by @fengttt

**Comment by daviszhen** [comment]
related to #6629

**Comment by fengttt** [comment]
given a new config/launch file, so that we can bring the system up in different setting -- for example, if a perf run failed, we just want to look at logs etc, we may want to bring it up on a single node.

maybe a good idea to put a lock file somewhere so that we do not accidentally bring up the system in more than one cluster.   But I assume this is a lesser issue if we mainly use this as debugging tool.
