### ISSUE TITLE
segment storage change for dynamic index operations

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#1166]
Currently, all segment indices are created at the same time as the segment. To support index dynamic drop and create, we need to change the underlying segment storage

**Comment by zzl200012** [comment]
### Proposal: support Create/Drop Index in AOE
For supporting dynamic create/drop index(basically bit-sliced index a.k.a BSI), we decide
to separate bsi as an independent file, which is built and destroyed under control instead
of sharing the same lifetime with .seg file. For the convenience of dropping, we make one
single file for each columns of a segment(e.g. 1_2_1.bsi => segment 1_2, column 1, a bsi).
This is just a temporary solution and errors like `too many files` are not taken into our
consideration.

**Create Index**:
  1. turn on the switch to make sure all the following sorted segment would be flushed with
     the given index on certain columns built as well.
  2. start the background worker generating index files for existing `.seg` file.
  3. update index related metadata atomically.
  ```
  Case 1:
  table_1 = [col_0, col_1]
  t1 -> seg_1  seg_2 seg_3
         |      |       \
         |      |        \
      1_1.seg  1_2.seg   [1_3_1.blk 1_3_2.blk xxx.tblk]

  Case 2:
  table_1 = [col_0, col_1]
  t1 -> seg_1 
         |
         |
      [1_1_1.blk 1_1_2.blk xxx.tblk]
  ```
  In case 1, after a period of time calling CreateIndex on table_1.col_1, it's expected
  to see the following files(let's say we do not append more data when seg_3 reached full):
  `1_1.seg 1_2.seg 1_3.seg 1_1_1.bsi 1_2_1.bsi 1_3_1.bsi`
  also this condition is possible before seg_3 is closed:
  `1_1.seg 1_2.seg 1_3_1.blk 1_3_2.blk 1_3_3.blk 1_1_1.bsi 1_2_1.bsi`
  but it's impossible that `1_3_1.bsi` is genereted but seg_3 still open.

  In case 2, obviously there would not be any index file until `1_1.seg` is generated.

**Drop Index**:
  1. remove all the related index files, and update index holder's status.
  2. update index related metadata atomically.

  Drop is pretty easy in our one-file-per-column design. I'll update here if any risk
  exists in future development.

**Conclusion**:
  - [ ] Phase 1: refactor the current index flushing procedure, separate BSI from others, and
  store bsi-per-column in a single file. Also a switch controlling flush or not is needed.
  - [ ] Phase 2: add `CreateIndex` interface so that we can create bsi for some column of some
  segment manually.
  - [ ] Phase 3: add `DropIndex` interface.
