### ISSUE TITLE
[Bug]: Load data from aliyun panic if the parameters are incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12194]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): fade9c43805334a358b017daf62dde891ef1c89d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1370" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/aeb2fadb-bc1d-47e7-87ca-08bead57f114">

### Steps to Reproduce

```Markdown
Load data from aliyun:

sql：load data url s3option {"provider"='aliyun', "endpoint"='oss-cn-shanghai.aliyuncs.com', "bucket"='lr90-bucket', "filepath"='customer.csv', "role_arn"='***',"provider"='minio',"compression"='auto'} into table customer  FIELDS TERMINATED BY '｜' ENCLOSED BY '\"' LINES TERMINATED BY '\n';
```

**Comment by aylei** [comment]
@reusee PTAL

**Comment by reusee** [comment]
This nil pointer deref issue was fixed in https://github.com/matrixorigin/matrixone/commit/0070abe134880d9b12e8b4108647a9ebd42fb7aa#diff-53c458acf1a3339cd979fff55fe0f53e01073eadae1e21b997ff1933461b6539R562

I don't think the reported commit id is correct, since the 527 line of aliyun_sdk.go does not contain any pointer deref
https://github.com/matrixorigin/matrixone/blob/fade9c43805334a358b017daf62dde891ef1c89d/pkg/fileservice/aliyun_sdk.go#L527

**Comment by Ariznawlll** [comment]
<img width="1434" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/885b6ad6-a2ec-4fa0-a85c-e785cf9f29a4">

Verifeid!

**Comment by reusee** [comment]
OK, re-assigning
