### ISSUE TITLE
[Subtask]: remove aggs from batch. make it an attribute of  the operator

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#12504]
### Parent Issue

#10729

### Detail of Subtask

remove aggs from batch. make it an attribute of  the operator

**Comment by aunjgr** [comment]
Some thoughts:

mergegroup and group operators should be in different pipelines, because mergegroup can receive data from group operator on remote nodes.

`Aggs` stores the intermediate results of aggregate function calculation, one or a few values per group. So it's feasible to convert it to vectors, and then append to the batch.

**Comment by ouyuanning** [comment]
目前batch已经不需在pipeline间复制了。这个可以关了
