### ISSUE TITLE
[Bug]: ERROR 1136 (HY000): `Column count doesn't match value count at row 1` when Upgrader Fails.

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#13038]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table vec_table(a int, b vecf32(3), c vecf64(3));
Query OK, 0 rows affected (0.42 sec)

mysql> create table vec_table2(a int primary key, b vecf32(3), c vecf64(3));
ERROR 1136 (HY000): Column count doesn't match value count at row 1

mysql> create table vec_table3(a int unique key, b vecf32(3), c vecf64(3));
ERROR 1136 (HY000): Column count doesn't match value count at row 1

It's supposed to work with table with primary key or unique key.

**Comment by arjunsk** [comment]
As mentioned in the earlier discussion, this is not specifically related to the Vector data type. 
![image](https://github.com/matrixorigin/matrixone/assets/9638314/111ac5e7-7b3f-4a45-832e-3ba21b282d4a)



It is due to a failure in Upgrader. I have added a relevant comment [there](https://github.com/matrixorigin/matrixone/issues/12262#issuecomment-1829483269).

**Comment by arjunsk** [comment]
This will be fixed in this PR: https://github.com/matrixorigin/matrixone/pull/13057

**Comment by arjunsk** [comment]
Waiting for the changes to be applied to the MO-Cloud instances.

**Comment by arjunsk** [comment]
This issue is tracked by https://github.com/matrixorigin/matrixone/issues/13038

The fix is merged. Kindly retest.

**Comment by dengn** [comment]
fixed.
