### ISSUE TITLE
[Bug]:  Many SQL failed around CN scale down due to `can not connect to remote backend.`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13789]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.0.2

### Commit ID

8081e05

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When the CN is scaling down, a large number of SQL executions resulted in errors(`can not connect to remote backend.`). This issue persisted for approximately 6 minutes.

http://121.43.41.174/explore?panes=%7B%22ahJ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%2279307612-ae09-4fc0-81c3-e3f8b13a9927%5C%22%7D%20%7C%3D%20%60query%20trace%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703495880000%22,%22to%22:%221703496359000%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="899" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/b47f2741-9f9a-4084-8786-a147d32ee7f1">

### Steps to Reproduce

```Markdown
see https://github.com/matrixorigin/MO-Cloud/issues/2132
```

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
出现问题的原因是lockservice的探活存在一些问题，接下来提pr修复这个问题

**Comment by nnsgmsone** [comment]
fixed

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
commit: af101ee
DEV环境跑TPCC过程中进行扩缩容，还是会出现问题：
[benchmarksql-error-10-10.log](https://github.com/matrixorigin/matrixone/files/14031776/benchmarksql-error-10-10.log)

**Comment by tianyahui-python** [comment]
测试场景: 在1个cn场景下,执行tpcc业务, 按照junhong的说法,这时候执行事务会在这个cn上加锁(简单理解锁服务)， 当cn扩容到两个的时候, 再执行tpcc 业务, 当前链接会链接到第二个cn上执行sql, 此时 需要访问cn1上的锁服务, 这时候断开cn1上的tpcc 链接, 断开扩缩容业务, 发生缩容, 由于cn2上有session 链接, 所以会优先缩容cn1，这时候再执行cn2上的tpcc业务, 需要先访问cn1上的锁服务, 所以会报错:" can not connect to remote backend"

测试报告:
[benchmarksql-error-10-1.log](https://github.com/matrixorigin/matrixone/files/14050962/benchmarksql-error-10-1.log)

测试详情: 
[benchmarksql-info.log](https://github.com/matrixorigin/matrixone/files/14050968/benchmarksql-info.log)c

此处存在另一个bug:  在18:43:11 The connection has not been valid, caused by: Communications link failure 这个地方不应该导致链接断开(扩缩容bug, 另开issue跟踪)

结论: bug 已修复, 验收通过

**Comment by aressu1985** [comment]
closed
