### ISSUE TITLE
Add pure go version of function round

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#1497]

**Comment by broccoliSpicy** [comment]
Fun facts about round(it is actually boring though):
    For float point numbers, mysql and ClickHouse dealt differently in the .5 situation, 

   --------- mysql ----- ClickHouse

   3.5 >>>>> 4 >>>>>>>>>   4
   4.5 >>>>> 5 >>>>>>>>>   4
  -3.5 >>>> -4 >>>>>>>>> -4
  -4.5 >>>> -5 >>>>>>>>> -4

mysql rounds .5 away from zero, ClickHouse round .5 to the nearest even number([banker's rounding rule](https://en.wikipedia.org/wiki/Rounding))

Rounding to the nearest even number is the default rounding mode used in IEEE 754 operations for results in binary floating-point formats

Intel introduces round instruction since SSE 4.1, this instruction rounds .5 to the nearest even number(same as     ClickHouse).
