### ISSUE TITLE
table cardinality information management

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#1575]
> Requirement
1. Segment and table level cardinality approximate statistics info
2. Relatively low cost of updating
3. Persistent and easy to use

**Comment by yingfeng** [comment]
Take [this implementation](https://github.com/axiomhq/hyperloglog) as a reference due to it's internal `merge` interface. There should exist a cardinality estimation for each column within each segment.
If the `intersection` is also required, take [this](https://github.com/axiomhq/hyperminhash) as a reference, but perhaps it has nothing to do with what we are wanted.
