### ISSUE TITLE
[Bug]: The vector query bvt test result is incorrect

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#17845]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

029a4f020e4561cd77c37d6f03d6b63414052ea9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /home/runner/work/matrixone/matrixone/test/distributed/cases/vector/vector_index.sql
[ROW    NUMBER]: 108
[SQL STATEMENT]: select * from vector_index_08 where a>9774 order by  L2_DISTANCE(d,"[1.02,0.2,3.2]") desc limit 2;
[EXPECT RESULT]:
a    b    c    d
9778    null    null    [8.555, 2.11, 7.22]
9777    null    null    [2.36, 5.021, 9.222]
[ACTUAL RESULT]:
a    b    c    d
9777    null    null    [2.36, 5.021, 9.222]
9776    [10, 3, 8, 5, 48, 26, 5, 16, 17, 0, 0, 2, 132, 53, 1, 16, 112, 6, 0, 0, 7, 2, 1, 48, 48, 15, 18, 31, 3, 0, 0, 9, 6, 10, 19, 27, 50, 46, 17, 9, 18, 1, 4, 48, 132, 23, 3, 5, 132, 9, 4, 3, 11, 0, 2, 46, 84, 12, 10, 10, 1, 0, 12, 76, 26, 22, 16, 26, 35, 15, 3, 16, 15, 1, 51, 132, 125, 8, 1, 2, 132, 51, 67, 91, 8, 0, 0, 30, 126, 39, 32, 38, 4, 0, 1, 12, 24, 2, 2, 2, 4, 7, 2, 19, 93, 19, 70, 92, 2, 3, 1, 21, 36, 58, 132, 94, 0, 0, 0, 0, 21, 25, 57, 48, 1, 0, 0, 1]    3    [0, 0, 0]

### Steps to Reproduce

```Markdown
Non essential errors that occur during CI testing
```

**Comment by arjunsk** [comment]
Debugging.

**Comment by arjunsk** [comment]
This issue occurs because when the index is created for column `d`, it is created with all zero vectors. This results in 3 centroids which are all zero vectors
![image](https://github.com/user-attachments/assets/12d4fb86-5eaf-4fd3-aa57-ecd953624e91)

This results in mapping the entries into either on of the zero vectors as every centroid can have an equal probability of owning the member.
![image](https://github.com/user-attachments/assets/988d1565-929a-4416-abad-4b2131ba4af3)

**Comment by arjunsk** [comment]
This should fix this issue: https://github.com/matrixorigin/matrixone/pull/17876

**Comment by arjunsk** [comment]
PR merged to master.
