### ISSUE TITLE
[Feature Request]: Suggest to support postgresql syntax

### ISSUE THREAD

**Issue by mojerro** [matrixorigin/matrixone#1862]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

Many OLAP databases and some of my projects are based on pg, and I also wonder will matrixone support multi-sql-language at the same time with one engine, and I will only need to maintain one database

**Comment by yingfeng** [comment]
Hi, @mojerro , thanks for your attention!
Actually, we have the plan to provide multiple sql dialects including postgresql start from scratch, that's one of the reason why we write our [own parser](https://github.com/matrixorigin/matrixone/tree/main/pkg/sql/parsers) instead of using existing one such as tidb's parser and you could see multiple sql dialects could co-exist [there](https://github.com/matrixorigin/matrixone/tree/main/pkg/sql/parsers/dialect). However, it requires lots of further developments although we've set up the framework already. Open source contribution is welcome!

**Comment by fengttt** [comment]
wont do.
