### ISSUE TITLE
[Bug]: panic while calling builtin function with constant value as input parameter in `select statement` if the result is more than one row.

### ISSUE THREAD

**Issue by noneback** [matrixorigin/matrixone#2026]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f425f88b
- Hardware parameters: Intel i5-8250U (8)
- OS type: Arch Linux x86_64 Kernel: 5.16.14-arch1-1
- Others: go version go1.17.8 linux/amd64
```

### Actual Behavior

exit with panic

### Expected Behavior

should return the correct result with built-in function output.

### Steps to Reproduce

```markdown
1. use some db with a table having more than one row.
2. select pi() from table_name limit 1;  (it works fine.)
3. select pi() from table_name limit 2; (it will panic).
```

**Comment by m-schen** [comment]
it's due to pi() only return a vector with single row. So it will panic at front-end.
It's a common bug at MO now. 
Such SQLs will cause panic.
1. `select a, 1 from t;`
2. `select a, pi() from t;`
3. `select pi() from t;`

And we will find a suitable way to solve it. 
Also with this modification, we hope to support the following use cases as well if possible
1. `select 1 from t;` (it will return n rows of value 1, and n is row number of t.)
