### ISSUE TITLE
[Question]:  Tutorial about agg function development

### ISSUE THREAD

**Issue by noneback** [matrixorigin/matrixone#2059]
### Question about agg function development

The tutorial takes `var` as an example to show how to develop an agg function. Although it is quite clear about the developing steps , it still puzzles me.
Such as those codes following:
```golang
// VarRing is the ring structure to compute the Overall variance
type VarRing struct {
 // Typ is vector's value type
 Typ types.Type

 // attributes for computing the variance
 Data []byte    // store all the Sums' bytes
 Sums  []float64 // sums of each group, its memory address is same to Dates

 Values [][]float64  // values of each group
 NullCounts []int64   // group to record number of the null value
}
```
1. Is `Data` related to `Sums` as the comment saying they share the same address? How and Why?

2. In an example about developing the `var` agg function, I haven't seen any code about variance calculation, but all about the `ring` interface instead. After reading all those contents, I have little knowledge about how the agg and `ring` work correctly. Can you show me where is the code about `variance calculation` so that I can have a better understanding?

**Comment by m-schen** [comment]
For question 1:
 Date and Sums point to the same address. We get this memory from memory pool. And others using Golang's make function.
 And why we should have a data ? This is helpful for us to do serialization for Ring, and finally we will return a vector to store the aggregate result, vector need a data attribute.

For question 2:
 Where the calculation is performed depends on what aggregate function it is and how you implement it.
 Let me give you two brief examples `max` and `variance`
 Max :  we do calculation work at functions Fill(), Add(), Mul(), when we get a new row or another ring, we should update the max values. And finally return it at Eval() function.

 But Variance is different. We need all the values to calculate it. So we get the sum of each group and store values of each group at Fill(), Add(), Mul() functions. 
 At last, in function Eval(), we calculate the avg number of each group by Sums, and calculate the variance. 
(This may not be a good implementation because we are recording too much data during the calculation, which requires a lot of space, so it is just an example)

The documentation only describes the implementation process, please refer to the code for more details. @noneback

**Comment by noneback** [comment]
Thx for your answer!
