### ISSUE TITLE
[Enhancement]: golang's precision of float is different between amd64 and arm64

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#2125]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
I found that there are some unit test in Matrixone will check the result which type is float64.

For Example, in `pkg/vectorize/exp/exp_test.go`,
it will check if result is 2.3538526683702e+17 using `reflect.Equal`
it's a inaccurate number.

And Golang's float has different precision between amd64 and arm64
this will make the unit test can only pass at one of them, and the other will failed.
```

**Comment by cnutshell** [comment]
Related issue #2403

**Comment by cnutshell** [comment]
The unit tests for package github.com/matrixorigin/matrixone/pkg/vectorize/exp were ok under GOHOSTOS="linux"; GOHOSTARCH="amd64", but were failed under GOHOSTOS="darwin"; GOHOSTARCH="arm64".

Maybe we should check reasonability for these unit tests in order to keep their compatibility and accuracy.

**Comment by cnutshell** [comment]
Issue resolved in a very `clever` way.
