### ISSUE TITLE
[Bug]: agg node is lost

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2838]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Node: TABLE_SCAN

### Steps to Reproduce

```markdown
create table t1 ( a int not null default 1, big bigint unsigned);
insert into t1 (big) values (12345678901234567),(9223372036854775807),(18446744073709551615);
select max(big)-1 from t1;
```

**Comment by aressu1985** [comment]
fixed 

mysql> create table t1 ( a int not null default 1, big bigint unsigned);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t1 (big) values (12345678901234567),(9223372036854775807),(18446744073709551615);
Query OK, 3 rows affected (0.01 sec)

mysql> select max(big)-1 from t1;
ERROR 1105 (HY000): Can't cast column from BIGINT UNSIGNED type to BIGINT type because of one or more values in that column. Reason: overflow
mysql> select max(big)   from t1;
+----------------------+
| max(big)             |
+----------------------+
| 18446744073709551615 |
+----------------------+
1 row in set (0.01 sec)

mysql>
