### ISSUE TITLE
[Feature Request]: Distributed transaction server

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#3116]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
Distributed transactions are implemented by the transaction coordinator at the DN node, as well as interacting with the transaction operations of the storage TAE.
```

### Describe the feature you'd like

Provides coordination and storage capabilities for distributed transactions

**Comment by zhangxu19830126** [comment]
@XuPeng-SH As per the afternoon discussion, some interfaces need to be confirmed by the engine. [Interface definitions](https://github.com/zhangxu19830126/matrixone/blob/txn_service/pkg/txn/service/types.go)

* ReadResult
* WaitTxns

**Comment by zhangxu19830126** [comment]
@XuPeng-SH @triump2020 @lni @zhangxu19830126 Think together about how TAE handles multiple processing of the same request due to network reasons

**Comment by triump2020** [comment]
To support the exactly-once semantics  of RPC  is not a easy thing  if we take into account  retries/attempts of a request from the same client may  send to different DataNodes  in different terms.    [http://web.stanford.edu/~ouster/cgi-bin/papers/rifl.pdf](url)

**Comment by triump2020** [comment]
[In the flow chart of the distributed transaction](https://github.com/matrixorigin/docs/blob/main/design/transaction2/write_commit.png) ,  there is one such corner case :  
  1.  The coordinator **parallelly**  issues a commit  to  participant. 
  2.  The participant receives the commit request and commits the transaction virtually.
  3.  The coordinator breaks down before receving the ack from participant ,  that is to say the txn's status is still **prepared** .
  4.  After the coordinator reboots , it needs to resolve  the actually status of the txn ,  so it issues a query by **TID**(transaction id)  to participant ,  unfortunately there is no TID in the participant since the txn relates to this TID has been committed , all of the txn's meta info has been droped.
  
   How to solve it ?    As per our discussion,   one way to solve this problem  is  to let the coordinator don't issue the commit to participant until  it updates successfully  the status of the transaction to **committed**. 

  May be this way is not very qualified since it increased  the latency of  distributed tranaction.

**Comment by lni** [comment]
docs -
https://github.com/matrixorigin/docs/tree/main/design/transaction2
