### ISSUE TITLE
[Bug]: Ceil function result wrong

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3316]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

create table t(a double);
insert into t select (CEILING(18446744073709551615));
insert into t select (FLOOR(18446744073709551615));
select * from t;
drop table t;

[SQL STATEMENT]: select * from t;
[EXPECT RESULT]:
a
1.8446744073709552E19
1.8446744073709552E19
[ACTUAL RESULT]:
a
-1.0
-1.0

[SQL STATEMENT]: select ceiling(cast(-2 as unsigned)), ceiling(18446744073709551614), ceiling(-2);
[EXPECT RESULT]:
ceiling(cast(-2 as unsigned))	ceiling(18446744073709551614)	ceiling(-2)
18446744073709551614	18446744073709551614	-2
[ACTUAL RESULT]:
ceiling(cast(-2 as unsigned unsigned))	ceiling(18446744073709551614)	ceiling(-2)
18446744073709551614	-2	-2

**Comment by dongdongyang33** [comment]
create table t(a double);
insert into t select (CEILING(18446744073709551615));
insert into t select (FLOOR(18446744073709551615));
select * from t;
drop table t;

[SQL STATEMENT]: select * from t;
[EXPECT RESULT]:
a
1.8446744073709552E19
1.8446744073709552E19
[ACTUAL RESULT]:
a
-1.0
-1.0

**CURRENT  [ACTUAL RESULT]:**
 a                    
18446744073709552000 
18446744073709552000


I think this case issue is gone.

**Comment by dongdongyang33** [comment]
[SQL STATEMENT]: select ceiling(cast(-2 as unsigned)), ceiling(18446744073709551614), ceiling(-2);
[EXPECT RESULT]:
ceiling(cast(-2 as unsigned)) ceiling(18446744073709551614) ceiling(-2)
18446744073709551614 18446744073709551614 -2
[ACTUAL RESULT]:
ceiling(cast(-2 as unsigned unsigned)) ceiling(18446744073709551614) ceiling(-2)
18446744073709551614 -2 -2

** CURRENT [ACTUAL RESULT]:**
overflow from bigint to bigint unsigned 


this is a new issue caused by PR https://github.com/matrixorigin/matrixone/pull/3434
Create a new issue #3550  for it
