### ISSUE TITLE
[Bug]: drop table in wrong database gives wrong error message

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3769]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6e20c2b69a253d9cd476f2fea506fb067904f288
- Hardware parameters: mac m1 Arm, 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

After mo-server is launched, we don't choose any database yet. 
And try to delete a table:

mysql> drop table PARTSUPP;
ERROR 1105 (HY000): tae catalog: not found

### Expected Behavior

Give an error message like: 
ERROR 1051 (42S02): Unknown table 'database.partsupp'

**Comment by JinHai-CN** [comment]
Error message and error code need to refactor.
Related to #3435

**Comment by xzxiong** [comment]
After start new session, try to delete a table, without choose any database.
It should throw error like: `ERROR 1046 (3D000): No database selected` as following case:

**Expected Behavior**

// while non-selected database
mysql> drop tables not_exist;
ERROR 1046 (3D000): No database selected

// after selected database
mysql> use test;
Database changed
mysql> drop tables not_exist;
ERROR 1051 (42S02): Unknown table 'test.not_exist'

**Comment by xzxiong** [comment]
report current error result:
```
mysql> drop table not_exist;
ERROR 20403 (HY000): no such table system.not_exist
```
