### ISSUE TITLE
[Bug]: LEFT(str, len) occurs type transfer error between String and INT

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5510]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Table Structure : 
DROP TABLE IF EXISTS t;
CREATE TABLE t(
    id INT,
    str1 VARCHAR(20),
    str2 CHAR(20),
    PRIMARY KEY (id)
);

DML : 
INSERT INTO t VALUES (123456, 'anike1001@gmail.com', 'googood'), (123457, 'nitin5438@yahoo.com','hainghing');

SELECT * FROM t;

The problematic SQL stmt is : 
SELECT LEFT(id, '1'+2), LEFT(str1, '1'+'1'), LEFT(str2, '1'+'0') FROM t;

It's result : 
+-----------------+-------------------+-------------------+
| left(id, 1 + 2) | left(str1, 1 + 1) | left(str2, 1 + 0) |
+-----------------+-------------------+-------------------+
| 123             | anike1001@g       | googood           |
| 123             | nitin5438@y       | hainghing         |
+-----------------+-------------------+-------------------+

The Question is : '1' + 2 = 3,  '1' + '1' = 11.

**Comment by qingxinhome** [comment]
The reason for this problem is:
The support for implicit conversion of string subtraction and string computing technology is incomplete. After confirmation with the product colleagues, this problem will be investigated and solved later. @domingozhang @ouyuanning @goodMan-code @daviszhen

**Comment by tianyahui-python** [comment]
@goodMan-code pls talk with @domingozhang to make sure that if we should put this issue to 0.7 release

**Comment by goodMan-code** [comment]
Is there any progress on this issue

**Comment by qingxinhome** [comment]
There is no problem with the implementation of the left function. The reason for this bug is:
The number string addition operation is inconsistent with MySQL,
In mo, string concatenation is performed when adding numeric strings, and the return value type is string：
mysql> select '1'+'3';
+-------+
| 1 + 3 |
+-------+
| 13    |
+-------+

In MySQL, when adding numbers and strings, the strings will be converted to corresponding numerical values, and then the arithmetic addition will be performed. The return value type is numeric
mysql> select '1'+'3';
+---------+
| '1'+'3' |
+---------+
|       4 |
+---------+
This issue can be closed, and another issue can be mentioned。 @goodMan-code

**Comment by matrix-meow** [comment]
Hello @goodMan-code. The bug issue in the BVT test code has not been removed,issues automatically open.
