### ISSUE TITLE
[Bug]: CN-DN BVT Performace Tuning

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#5910]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/39627130/197513311-4b3f1711-8d7f-4f2f-8317-c6d6549881c2.png">

The BVT running time is many times that of the stand-alone deployment.

**Comment by fengttt** [comment]
We need a profiling for bvt run.   Please attach the result here.

**Comment by nnsgmsone** [comment]
The reason for the problem is that it takes too much time to fetch the table meta information. I added a lru cache that mitigates this nicely. This is the old pprof:
![old](https://user-images.githubusercontent.com/31609524/197672903-d2bcb1ed-0722-4608-b78c-08a9318228ad.png)
this is the new pprof:
![new](https://user-images.githubusercontent.com/31609524/197672934-7c753d6c-2696-40c2-a5ad-1dbb43c1e334.png)

**Comment by fengttt** [comment]
@nnsgmsone What is the running time of BVT?   CN/DN vs. TAE only

**Comment by nnsgmsone** [comment]
> @nnsgmsone What is the running time of BVT? CN/DN vs. TAE only

let me try TAE only.

**Comment by nnsgmsone** [comment]
Tae's runtime is 41s, and the improved cn-dn is 2m. But this improvement should be wrong.... I'd better do it with index. @fengttt

**Comment by nnsgmsone** [comment]
Adding indexes to the system tables would take me more time to process this. My understanding of the effect should be able to approach the wrong version of using LRU.

**Comment by nnsgmsone** [comment]
The main bvt elapsed time is about 6m30s

**Comment by fengttt** [comment]
Wait for permission cache.

**Comment by XuPeng-SH** [comment]
done
