### ISSUE TITLE
[Subtask]: Standalone Temporary Table

### ISSUE THREAD

**Issue by JackTan25** [matrixorigin/matrixone#6039]
### Parent Issue

#3428

### Detail of Subtask

To implement TempTable, We need to do the standalone version first

**Comment by jensenojs** [comment]
The problem now is that it is not compatible with engines in the 0.5 period. So that bvt for e2e ci can pass, but for ci can't.  We think it would be too redundant to be compatible with the 0.5 period engine, but what to do next needs to be interfaced with the storage at the same time to see whether to delete the 0.5 period engine or find a way around it

**Comment by JackTan25** [comment]
please merge https://github.com/matrixorigin/matrixone/issues/3428, accelerate

**Comment by JackTan25** [comment]
jensen is fixing bugs
