### ISSUE TITLE
[Performance]: Loading data is 3x slower when using multi-column primary key

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#6123]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

I ran tpch 10G data load twice. The first time, it's loading the `orders` table with original schema. The second time, I rewrite the primary key line as `PRIMARY KEY (O_ORDERKEY, O_CUSTKEY), others are the same. Single column pkey test costs 2.1 minutes, while 5.9 minutes for multi column pkey.

Below are the go pprof cpu profiles:
[cpu.prof.single.gz](https://github.com/matrixorigin/matrixone/files/9898650/cpu.prof.single.gz)
[cpu.prof.multi.gz](https://github.com/matrixorigin/matrixone/files/9898651/cpu.prof.multi.gz)

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by bbbearxyz** [comment]
the reason is when use multi primary key, system will create a extra composite primary col, the type is varchar. when insert values into table, the system will serial many priamry key cols into one. for example, table t(a int, b int, primary key(a, b)), when insert into table values(1, 1), the system will encode to one col. 

But the extra composite primary col is varchar and also it is primary key, the engine will make sure primary key is unique, when primary key type is varchar, the process that make sure unique is slow. So the problem happened.

I run three situation in the server, fisrt composite primary key, when insert tpch 1G data, the time is 8.5s. second situation when I just delete all the primary key, but I keep the process to build extra composite primary col, the time is 4s. third the table is just have one single primary key, the time is 5.5s. 

the three situation profs is below.
[test.prof.zip](https://github.com/matrixorigin/matrixone/files/9919404/test.prof.zip)

**Comment by aunjgr** [comment]
It will be fixed after tae migrated to new vector implementation.
