### ISSUE TITLE
[Bug]: results of TPCH 10G Query are different for the same test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6525]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b9c225f4f44dcd62d6f577394d705b6aed55188e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

run tpch 10G queries for 10 times , but the result ares different .
Mainly concentrated in Q8, Q9 and Q14

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/47846308/201476596-50937a83-ce7f-466f-99cf-76aca989c427.png">

### Additional information

[tpch_reprot.tar.gz](https://github.com/matrixorigin/matrixone/files/9995065/tpch_reprot.tar.gz)

**Comment by aressu1985** [comment]
and Q11 is NULL， it is also inconrrect

this is result from ck for the same data

[tpch10G.tar.gz](https://github.com/matrixorigin/matrixone/files/9996371/tpch10G.tar.gz)

**Comment by m-schen** [comment]
related to #6537

**Comment by nnsgmsone** [comment]
The reason for the Q9 and Q14 result error is that there is a bug with like. Please fix this.

**Comment by nnsgmsone** [comment]
> and Q11 is NULL， it is also inconrrect
> 
> this is result from ck for the same data
> 
> [tpch10G.tar.gz](https://github.com/matrixorigin/matrixone/files/9996371/tpch10G.tar.gz)

The ck's result is wrong, and I don't think it's appropriate to use ck to verify the correctness of tpch. clickhouse's behavior is not exactly as expected. @aressu1985

**Comment by aunjgr** [comment]
The result of Q19 has wrong scale. DECIMAL(*,2) * DECIMAL(*,2) should always be DECIMAL(*,4). `38030748.8555` is a valid result, but `38030749` is not. At least it should be `38030749.0000` for the sake of scale. In addition, Q8/Q14/Q19 should have deterministic results since all operands are DECIMAL, no floats/doubles. 

But we won't do a special fix for this. The 3rd-party decimal library we are using is an unmaintainable blackbox. I'm doing a rewriting in #4241. The decimal precision/scale related issue are all expected to be fixed (and well defined) when #4241 is done.

Q11 is different. The Q11 in tpch's [specification](https://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v3.0.1.pdf) is
```sql
select
ps_partkey,
sum(ps_supplycost * ps_availqty) as value
from
partsupp,
supplier,
nation
where
ps_suppkey = s_suppkey
and s_nationkey = n_nationkey
and n_name = '[NATION]'
group by
ps_partkey having
sum(ps_supplycost * ps_availqty) > (
select
sum(ps_supplycost * ps_availqty) * [FRACTION]
from
partsupp,
supplier,
nation
where
ps_suppkey = s_suppkey
and s_nationkey = n_nationkey
and n_name = '[NATION]'
)
order by
value desc;
```
and FRACTION is 0.0001 / SF. For 10G data, SF = 10. We are using static queries which are generated for SF = 1, so the result is empty. I modified Q11 accordingly, and it output non-empty result.

**Comment by m-schen** [comment]
compare with snowflake with size 1G. the result is correct expect the decimal precision.

**Comment by aressu1985** [comment]
@m-schen so what about the decimal precision?

**Comment by goodMan-code** [comment]
some tips for reference : 
1. ClickHouse's TPCH Query statement is different from https://github.com/aressu1985/mo-tpch/queries
2. use https://github.com/aressu1985/mo-tpch/queries,  I have test on SnowFlake 10G and 100G, as I got, Q11 is empty.

**Comment by goodMan-code** [comment]
for this issue, I will test more times ( 10G, at least 30), as I have got, Q11 may be empty, same as SnowFlake_10G

**Comment by goodMan-code** [comment]
I have run TPCH 10G 23 times, for q8's result : 
First time:
o_year  mkt_share
1995    0.03955424769916201
1996    0.03846446765981475
Second time:
o_year  mkt_share
1995    0.03955424769916201
1996    0.03846446765981475
Third time:
o_year  mkt_share
1995    0.039554247699162
1996    0.03846446765981475
fourth time:
o_year  mkt_share
1995    0.03955424769916201
1996    0.038464467659814754
fifth time:
o_year  mkt_share
1995    0.039554247699162
1996    0.03846446765981475

**Comment by aressu1985** [comment]
tracked by #4241 , and this closed
