### ISSUE TITLE
[Enhancement]: types.TS compare is not efficient

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#6734]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
The current types.TS.Compare is not efficient and it is on the critical path. We need to revisit types.TS
```

**Comment by cnutshell** [comment]
Now `types.TS` compares the raw bytes of `int64` and `uint32` with the help of package `unsafe` which would lead to extra overhead. After writing some benchmark, comparing timestamp at its original type (int64 and uint32) would be the most efficient way. So change the type of `types.TS` from raw bytes as to structure with an `int64` and `uint32` field would be the solution.

But it's not straightforward, because `types.TS` has been involved in read/write logic. We couldn't change the data type of `types.TS` directly. I'll resume this task after more investment.

**Comment by XuPeng-SH** [comment]
not needed
