### ISSUE TITLE
[Proposal]: vector: use Pointer instead of interface{}

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#6820]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
The current Vector uses an interface, and the current use of interfaces is causing some performance problems. I recommend using pointers instead of interfaces to indicate different types to get better performance.
```

**Comment by nnsgmsone** [comment]
# Abstract
The current Vector use interface{}, and the current use of interface{} is causing some performance problem. I recommend using pointer instead of interfaces to indicate different types to get better performance.
# Background
We originally used interface{} to represent different vectors, such as []int8, []int16... While this is a better practice, it does lead to some performance problems. go's interface{} leads to a lot of allocations, which then leads to a lot of gc and finally affects performance.
# Proposal
I propose use pointer instead of interface{} for better performance, and replacing interface{} with pointer can even make the structure more concise.
I propose the following Vector:
```go
type Vector struct{
    // other original fields
    ptr unsafe.Pointer // replace the original col and data fields
}
```
# Benchmark
I wrote a simple performance test with the following benchmark result:
```
cpu: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
BenchmarkOldVec-20     	52019065	        86.83 ns/op
BenchmarkNewVec-20    	1000000000	         0.6162 ns/op
```
The test code is as follows:
```golang
func BenchmarkOldVec(b *testing.B) {
    vec := new(vector0)
    {
        vs := make([]int8, 100)
        for i := 0; i < 100; i++ {
            vs[i] = int8(i)
        }
        vec.data = types.EncodeSlice(vs)
        vec.colFromData()
    }

    for n := 0; n < b.N; n++ {
        vec.colFromData()
    }
}

func BenchmarkNewVec(b *testing.B) {
    vec := new(vector1)
    {
        vs := make([]int8, 100)
        for i := 0; i < 100; i++ {
            vs[i] = int8(i)
        }
        data := types.EncodeSlice(vs)
        vec.SetPtr(data)
    }
    for n := 0; n < b.N; n++ {
        vec.GetPtr()
    }
}

```

**Comment by nnsgmsone** [comment]
As for the performance caused by interface{}, you can see several issues on aunjgr, such as #217 in cloud.

**Comment by nnsgmsone** [comment]
please review @reusee  @fengttt  @aunjgr

**Comment by fengttt** [comment]
As long as you hide impl detail cleanly this time.

Adding GuoKe.

**Comment by nnsgmsone** [comment]
o

> As long as you hide impl detail cleanly this time.
> 
> Adding GuoKe.

Oh, does this need to be handled by him.

**Comment by nnsgmsone** [comment]
ok

**Comment by fengttt** [comment]
This benchmark does not look meaningful -- I think the main cost of colFromData is a big type switch inside the code.   On this other hand, I'd agree this colFromData is unnecessary if we use raw pointer.

**Comment by fengttt** [comment]
The root of all evil is vector.Col is not private.

**Comment by nnsgmsone** [comment]
I col must be private, then the core issue col and data must be one thing, now it is two things, there is an additional conversion.

**Comment by cnutshell** [comment]
> There is some context information to be provided:
> 
> * in which package, the vector type was implemented
> * for what operation, we want to improve its performance

or how can I fetch the profiling code? I need to investigate this performance issue locally.

**Comment by nnsgmsone** [comment]
> > There is some context information to be provided:
> > 
> > * in which package, the vector type was implemented
> > * for what operation, we want to improve its performance
> 
> or how can I fetch the profiling code? I need to investigate this performance issue locally.

aunjgr will help you how to profiling.

**Comment by nnsgmsone** [comment]
I now think it might  be a bad idea to use pointer, it's too dangerous to write it that way and it's easy to write it wrong. I feel like this would create too much danger for the project. Maybe using a paradigm is the right way to go.

**Comment by aunjgr** [comment]
The problem is that using a pointer to hold the slice can't eliminate heap allocations.

The least impacting way is to keep Col but not update it for every UnionOne. We should make a slice whose cap=len when allocation happens, and maintain the real length simply by a int. Thus we don't need to assign a new slice to Col every time vector.extend is called.

**Comment by cnutshell** [comment]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/20291742/203303559-d3891e85-afe5-48d7-a280-585062955a0c.png">
According to the profiling result from @aunjgr , the performance issue is mainly caused by heap allocation.

I suggest that we should change the API of `DecodeFixedCol` which is heavily invoked under [*Vector.colFromData](https://github.com/matrixorigin/matrixone/blob/56bc90513f2d5dfeb21c3ecbb75c286507d58401/pkg/container/vector/tools.go#L158). `DecodeFixedCol` should accept a slice in order to avoid heap allocation. 

That's the API pattern that we should pay attention to: if the API didn't accept an area of memory, but it return an area, then the golang compiler would place the returned area to heap according to its `escape analysis`. In general, sharing up escapes to the heap and sharing down stays on the stack.

**Comment by cnutshell** [comment]
> Another problem for pointer is that MustTCols can't have type assertion guard. That makes using vector more dangerous.
> 
> By the way, our function implementations still have misuse/abuse of vector.Col.

Agree with @aunjgr. 
Package `unsafe` contains operations that **step around the type safety of Go programs**.
Avoid using it **unless you know what you are doing** and **you need the performance** improvements that it provides.

**Comment by nnsgmsone** [comment]
Since we all think the pointer is not a good suggestion, I'll close the proposal.

**Comment by cnutshell** [comment]
The following is the benchmark for [Vector.Col](https://github.com/matrixorigin/matrixone/blob/56bc90513f2d5dfeb21c3ecbb75c286507d58401/pkg/container/vector/vector.go#L44):
```go
func randInt8Slice(length int) []int8 {
    s := make([]int8, length)
    for i := 0; i < len(s); i++ {
        s[i] = int8(rand.Intn(math.MaxInt8))
    }
    return s
}

var gi interface{}

func BenchmarkVector(b *testing.B) {
    mp := mpool.MustNewZero()

    vs := make([]*Vector, 30000)
    for i := 0; i < len(vs); i++ {
        v := New(types.Type{Oid: types.T(types.T_int8)})
        v.data = mustMakeSliceArgsAsBytes(mp, randInt8Slice(24)...)
        vs[i] = v
    }

    b.ResetTimer()
    var li interface{}
    for i := 0; i < b.N; i++ {
        v := vs[i%len(vs)]
        li = types.DecodeSlice[int8](v.data)
    }
    gi = li
}
```

Place this code in file `github.com/matrixorigin/matrixone/pkg/container/vector/vector_test.go`, then run it:
```bash
go test -run none -bench Vector -benchmem -memprofile mem.out
goos: darwin
goarch: arm64
pkg: github.com/matrixorigin/matrixone/pkg/container/vector
BenchmarkVector-8       54177700                21.40 ns/op           24 B/op          1 allocs/op
PASS
ok      github.com/matrixorigin/matrixone/pkg/container/vector  1.812s
```

Via `go tool pprof -alloc_space mem.out`, the allocated memory lies in where we assign `unsafe.Slice` to an interface. In order to get rid of this unnecessary heap allocation, we must assign the value returned by `unsafe.Slice` to its corresponding concrete type (in this benchmark, the corresponding concrete type of `li` should be `[]int8`).
Change the type of variable `li` from `interface{}` as `[]int8`, then rerun this benchmark, you would see that here was no allocation each operation.

Hence there are  two ways  to optimize: 
1. change the type of field `Vector.Col` from `interface` as concrete type `[]T`;
2. or get rid of `Vector.Col`, access the underlying data via `unsafe.Pointer` where `Vector.Col` is needed.

**Comment by fengttt** [comment]
get rid of vector.Col is the right way,  I think :)

**Comment by cnutshell** [comment]
> get rid of vector.Col is the right way, I think :)

If getting rid of `Vector.Col`, we should wrap `unsafe.Pointer` related operation within proper API in order to avoid the abusing of `unsafe.Pointer`. All in all, keep safety via proper API design.

**Comment by cnutshell** [comment]
@fengttt Sorry to update this issue for a few days. After sync with @aunjgr last Wednesday, guys in the computing group would take this task during the release of `0.7.0`. And I would handle the other issues.
