### ISSUE TITLE
[Bug]: create function

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#7836]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

commit：fd59d2337a404ae91b233480c2a16c63cced8b85
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/216581168-d5d8b48c-4b81-4947-b14c-c39eedaaef00.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/108530700/216581226-30be6cb5-70a8-4723-a2b4-af2983635004.png)

**Comment by chrisxu333** [comment]
Currently the grammar for create a function should be: 
`CREATE FUNCTION function_name (argname argtype [{DEFAULT | = } default_expr] [, ...]) RETURNS return_type LANGUAGE language_name AS 'function_body' `
Hence instead of using `begin...end`, simply using '' would do the job. Also note that currently user-defined function body does not support compound statements like `return`. It may support it once stored procedure feature is implemented. 
Please refer to this doc for further detail. <https://github.com/matrixorigin/docs/blob/main/tech-notes/sql/design/udf_design_doc.md>
