### ISSUE TITLE
[Bug]:  SSB 100G Q1.2 was hung when running on EKS with 2*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7904]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 2db73d4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when run Q1.2 of SSB 100G query on distributed mo with 2 cn pod , the queries can not be return in about 3 hours

mysql> select sum(lo_revenue) as revenue
    -> from lineorder
    -> join date on lo_orderdate = d_datekey
    -> where d_yearmonthnum = 199401
    -> and lo_discount between 4 and 6
    -> and lo_quantity between 26 and 35;

.....

### Steps to Reproduce

```Markdown
SQL：
select sum(lo_revenue) as revenue
from lineorder
join date on lo_orderdate = d_datekey
where d_yearmonthnum = 199401
and lo_discount between 4 and 6
and lo_quantity between 26 and 35;
```

**Comment by dongdongyang33** [comment]
checking

**Comment by aressu1985** [comment]
mysql> explain select sum(lo_revenue) as revenue
    -> from lineorder
    -> join date on lo_orderdate = d_datekey
    -> where d_yearmonthnum = 199401
    -> and lo_discount between 4 and 6
    -> and lo_quantity between 26 and 35;
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Project                                                                                                                                                   |
|   ->  Aggregate                                                                                                                                           |
|         Aggregate Functions: sum(lineorder.lo_revenue)                                                                                                    |
|         ->  Join                                                                                                                                          |
|               Join Type: INNER                                                                                                                            |
|               Join Cond: (lineorder.lo_orderdate = date.d_datekey)                                                                                        |
|               ->  Table Scan on ssb_100g.lineorder                                                                                                        |
|                     Filter Cond: (lineorder.lo_discount >= 4), (lineorder.lo_discount <= 6), (lineorder.lo_quantity >= 26), (lineorder.lo_quantity <= 35) |
|               ->  Table Scan on ssb_100g.date                                                                                                             |
|                     Filter Cond: (date.d_yearmonthnum = 199401)                                                                                           |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
10 rows in set (2.53 sec)

**Comment by dongdongyang33** [comment]
no progress. 
fixing 7901 today

**Comment by dongdongyang33** [comment]
no progress.
fixing 7901 today

**Comment by dongdongyang33** [comment]
no progress
will begin tomorrow

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
A little bit similar to #7901, the pipeline message includes too much meta info about s3, so it is too big to send.

will separate the over-size message into chunks like sending a batch

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by nnsgmsone** [comment]
same as #8071

**Comment by aressu1985** [comment]
will test soon

**Comment by nnsgmsone** [comment]
The blocklist is too big. May need slicing

**Comment by fengttt** [comment]
田丰(fengttt) 2-27 09:48:34PM
@颜文泽(nnsgmsone)  TPCH 100G failure -- there is a really cute solution.   We can add an operator called metascan or zonemap scan, which will scan out the zonemap info given a predicate.   This zonemap scan then distribute scanned zonemap to different CN workers which will use the meta data to do real scan.   Note that we will make sure blocks in one S3 obj are sent to same CN (with best chance of a cache hit).    

田丰(fengttt) 2-27 09:48:46PM
So CN worker does not need to poll log tail.

田丰(fengttt) 2-27 09:49:31PM
And it will not hit rpc 100MB limit, because we produce zonemap in "batches"

田丰(fengttt) 2-27 09:50:01PM
meta scan, or zonemap scan is also useful in select count(*) and the size estimation.

田丰(fengttt) 2-27 09:50:40PM
So we really should just implement this function.   And this is an extremely powerful debug/analyze tool for later storage optmization.

田丰(fengttt) 2-27 09:51:38PM
Why don't we just implement this ...      select * from metadata_scan(table_name, column_list, expr_predicate);    

田丰(fengttt) 2-27 09:52:42PM
return columns includes s3 obj name, row count, null count, ndv, min, max, meta_location.

田丰(fengttt) 2-27 09:53:27PM
plus snapshot info of the block.

田丰(fengttt) 2-27 09:54:05PM
@崔国科(cnutshell)  maybe this is your work ...

田丰(fengttt) 2-27 09:55:50PM
but for execution, we may not need this formalism from parser etc, just implement this operator and hard code it in the plan.

**Comment by nnsgmsone** [comment]
Qin Xuan will start by fixing this code with a brutal approach.

**Comment by nnsgmsone** [comment]
Qin Xuan will start by fixing this code with a brutal approach.

**Comment by dongdongyang33** [comment]
code prepare. need to test

**Comment by nnsgmsone** [comment]
wait for qinxuan's pr

**Comment by dongdongyang33** [comment]
in process

**Comment by dongdongyang33** [comment]
add  `[cn.rpc] max-message-size = "1GB"` in cn config could resolve this issue

need Guoke‘s meta scan #8016 to solve it completely

**Comment by cnutshell** [comment]
To resolve this issue completely, I need to refactor metadata related logic.
I'm working on logtail push model which has the highest priority.
I'll pick this issue as soon as possible.

**Comment by fengttt** [comment]
Set message size to 1G is not an acceptable solution.

**Comment by aressu1985** [comment]
fixed
