### ISSUE TITLE
[Bug]: too much SyncLogTailReq make CN slow to respond query

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#8164]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.7.0
```

### Actual Behavior

This issue is separated from https://github.com/matrixorigin/matrixone/issues/8141, we observed abnormal amount of SyncLogTailReq and this makes CN slow to response query and hang eventually.

Log:
https://github.com/matrixorigin/matrixone/issues/8141#issuecomment-1445710430
https://github.com/matrixorigin/matrixone/issues/8141#issuecomment-1445691200

### Expected Behavior

CN should respond simple request (e.g. create new session) in a predictable amount of time.

**Comment by daviszhen** [comment]
After researching the log, I get the reason probablely.

the cloud platform executes the sql "show accounts like " for an account almost every minute.
"show accounts" evalutes the table size and the table rows of every table of every database for the account.
the impl of the "show accounts " depends on the functions mo_table_size and mo_table_rows that resync the logtail 
of the table.
If the table is opened at the first time, the logtail of the table should be resynced from  zero that costs many S3 io.
so, the behavior slows down the boot procedure and timeout finally.

Several suggestions:
1, storage provides instant table size and table row instead of evaluating them at the runtime.
2, split the sync of the logtail into table meta sync and table data sync.

**Comment by aylei** [comment]
cc @sukki37 @DanielZhangQD

**Comment by daviszhen** [comment]
After discussing with @cnutshell ，"too much logtail sync" caused by evaluating the table size and rows will be put on his schedule

**Comment by fengttt** [comment]
First, getting number of rows for all tables under an account, does this make any sense?    What does this number mean?

Second, I believe size, we need to get total storage usage?   If that is the case, is there an easier way to get ALL storage usage of an account from S3 api?

**Comment by cnutshell** [comment]
`SyncLogTailReq` is pull mode, now we take push mode as default, no need to handle this issue.

**Comment by sukki37** [comment]
This issue has been inactive for a while. To help keep our backlog clear, I'm going to close this. If you feel this is still relevant, please comment or reopen.
