### ISSUE TITLE
[Bug]: `count(*)` returns wrong result occasionally

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8256]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 093e0c58a05c760da2ded061c7dadc41b71652c9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/4290037359/jobs/7473645274

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/77312370/222940743-700b2b09-0600-4e25-937e-ed2bf0c6822b.png">

### Expected Behavior

bvt 100% pass 

### Steps to Reproduce

```Markdown
run bvt on multi-cn
```

**Comment by sukki37** [comment]
Maybe the same root cause as #7748

**Comment by nnsgmsone** [comment]
I will devote myself to dealing with this.

**Comment by nnsgmsone** [comment]
I reran a day with the latest code without recurrence.

**Comment by nnsgmsone** [comment]
If this problem does not recur after today I will reopen bvt, it turns out that the reason for this problem is probably because our data and metadata have two isolation levels (there is also an appended block) so special that reading data directly with a timestamp does not actually always get a correct data. #8267

**Comment by sukki37** [comment]
traced by #7748
