### ISSUE TITLE
[Feature Request]: metadata_scan

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8342]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
create a table value function, metadata_scan.
```

### Describe the feature you'd like

select * from metadata_scan('db.table', 'col');          col can be *, in this case get all columns.

return entries of metadata.    which should be a table like,

table metadata_scan (
   s3obj_name varchar,
   create_ts, timestamp,
   delete_ts timestamp,
   blockid int,
   col varchar,
   size int,
   compressed_size int,
   rowcount, nullcount, 
   min, max,
   del_loc
);

Ask jiangwei for the complete list of columns.

**Comment by fengttt** [comment]
Please just use existing CN code to retrieve all these info.   Leave @cnutshell for later optimization if necessary.

**Comment by nnsgmsone** [comment]
This will be handled after the operator refactoring, which is expected in two weeks.

**Comment by dongdongyang33** [comment]
now support metadata info:
`block_id`, `entry_state`, `sorted`,`meta_loc`, `delta_loc`,`commit_ts`, `meta_seg`, `rows_count`, `null_count`, `compress_size` and `origin_size`

Addition info:
1. metadata_scan is a table function like generate_series now. 
  1.1 The first parameter must db_name.table_name
  1.2 the second parameter must be a column belonging to the table specified by the first parameter. Or you can use `*` to get all columns' info of the table.
2. Because we can show all columns' info and they might have different types, so max and min are not added to the result now. will convert them to strings to show in the future.
3.  `s3obj_name varchar`, `create_ts ` and `delete_ts` are not included.

**Comment by aunjgr** [comment]
For particular column `col`, the type of min/max of `metadata_scan('db.table', 'col')` should be type of `col`.

For `metadata_scan('db.table', '*')`, it's OK to cast min/max as varchar.

**Comment by dongdongyang33** [comment]
the pr was reverted by #9737 

will update after re-merge to main

**Comment by Ariznawlll** [comment]
test done！

**Comment by dongdongyang33** [comment]
the SQL mo_table_size() behavior also changes with this pr.

**Comment by Ariznawlll** [comment]
> 

testing

**Comment by LeftHandCold** [comment]
is done
