### ISSUE TITLE
[Enhancement]: Optimizing garbage collection

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#9008]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Currently, we have many performance problems related to Go's garbage collection. We need to identify all code problems and do optimizations.
```

**Comment by XuPeng-SH** [comment]
![image](https://user-images.githubusercontent.com/39627130/232639900-ca34ca60-f580-4033-b3aa-1f4c4d3f3a8f.png)

@cnutshell Pls look into this problem when you are done with #7111

**Comment by fengttt** [comment]
@reusee please reevaluate this issue.

**Comment by reusee** [comment]
Most allocations come from disk/S3 I/O and uncompression during block prefetching.
The memory cache is caching the uncompressed bytes, making the peak memory larger than configured.
Either optimize the prefetching process or set a limit on buffers for uncompression. 
I prefer optimizing the prefetching with per-reader queues for IO instead of using unbounded prefetching.
Prefetches are pushing too many entries to the LRU, and many of those entries are never read before eviction.

**Comment by reusee** [comment]
the file service part is done. 
@nnsgmsone is working on the caller-side optimization.

**Comment by ouyuanning** [comment]
等fixed buffer优化完成后
要讨论下这个issue的验收标准。
