### ISSUE TITLE
[Bug]: User-defined functions isolate problems.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9044]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id：5177f3199b755fa0c67017a2f2e7be2fb6350c3e
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/232695428-b36e3f57-20ce-47e6-ad28-003a443e1a05.png)

### Expected Behavior

After use ttt, we should directly search for the function with the same name under ttt. If we cannot find it, an error will be reported.

### Steps to Reproduce

```Markdown
create database ttt02;
use ttt02;
create function hei() returns int language sql as 'select id from test_table limit 1';
create database ttt;
use ttt;
call hei();
```

**Comment by aunjgr** [comment]
@chrisxu333 I assume UDF issues belong to you. Please have a look.

**Comment by chrisxu333** [comment]
First of all I don't think UDF should be called using CALL (correct me if I'm wrong :), CALL is only used for stored procedure. UDF should be called in a query. As currently stored procedure execution is still waited to be code reviewed, CALL command will simply return ok and do nothing. In your experiment, if you want to test the UDF isolation problem, try to call the UDF inside a query, like select * from table where id = hei(), this will give the expected behavior as you described above.

**Comment by Ariznawlll** [comment]
![image](https://user-images.githubusercontent.com/108530700/236666493-68fa9341-4558-481b-8401-bf2cd77f06c0.png)

test done！
