### ISSUE TITLE
[Bug]: Uninstall matrixone operator and re-install it in a short time will lead to unexpected deletion of crd

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9285]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters: 6 nodes
- OS type:Ubuntu 20.04
- Others:
```

### Actual Behavior

1. Install matrixone opereator, then uninstall it, using `helm install/uninstall` command
2. In a very short time, install matrixone operator again, using `helm uninstall` command too
3. Matrixone operator will be installed as shown using `helm list -A`
4. Install mo using `kubectl apply -f mo.yaml` where the yaml file defines an mo cluster
5. Log services pod will be pulled up and running, but dn and cn will not be pulled up
6. Check event of logset,
```bash
kubectl describe logset -nmo-hn
``` 
<img width="809" alt="企业微信截图_62be037c-857c-4658-ae49-4c75622e4171" src="https://user-images.githubusercontent.com/46433151/236611143-a3bdba9f-d422-4cfe-9ce1-62fe4b74d48f.png">

it indicates that crd bucketclaims.core.matrixorigin.io is missing.
7. Check crd, and confirm it's missing
8. The reason seems to be that when `helm uninstall` command is executed, the crd is still under deletion, but if we `helm install` the operator again, it does not check if previous resources are really deleted.

### Expected Behavior

See above

### Steps to Reproduce

```Markdown
See above
```

### Additional information

See above

**Comment by aronchanisme** [comment]
as per discussed, @loveRhythm1990 pls kindly help take a look

**Comment by aronchanisme** [comment]
@loveRhythm1990 As per discussed, uninstalling operator using helm uninstall command is a rare operation only used in specific situation, for example, when testing is done and customer is recycling the testing resources. thus we will workaround this by using helm upgrade command to upgrade operator if necessary. As for the issue, pls kindly put some inputs in dos and revert it back to me when you're done.

**Comment by loveRhythm1990** [comment]
we rarely uninstall matrixone-operator, unless we are sure it will no longer used, uninstall operator is dangerous operation, typically:
* if we want upgrade matrixone-operator, we should use `helm upgrade` command
* if we want delete matrixone cluster, we should use `kubectl delete mo` command

I will add more documents about the behavior of `helm uninstall`, and some points should be noted. 
This problem can be fixed by add a helm pre-install hook, to check if a CRD is in deleting progress, if it is, we should stop the helm install and report failure. it is a little trick and we decide not to fix this problem

**Comment by aronchanisme** [comment]
closing it now
